language: node_js
node_js:
  - "5"
sudo: required
services:
  - docker
before_install:
  - npm install -g autochecker
script:
  - autochecker 2.1.8-alpine 2.3.0-alpine 2.1-alpine 2.1.9-alpine 2.2.4-alpine
